# Commons library specific golangci-lint configuration
# Libraries have stricter requirements than services

linters:
  enable:
    # Correctness
    - govet
    - errcheck
    - staticcheck
    
    # Code quality
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - goimports
    
    # Best practices
    - errname
    - errorlint
    - nilnil
    - nilerr
    
    # Performance
    - prealloc
    
    # Security
    - gosec
    
    # Style
    - revive
    - stylecheck
    - misspell    # Check for misspelled words
    
    # Complexity
    - gocyclo     # Cyclomatic complexity
    
    # Documentation (stricter for libraries)
    - godot  # Comments should end with period

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true
    
  govet:
    enable-all: true
    disable:
      - fieldalignment
    
  revive:
    rules:
      - name: var-naming
        severity: warning
      - name: context-as-argument
        severity: warning
      - name: error-return
        severity: warning
      - name: error-strings
        severity: warning
      - name: error-naming
        severity: warning
      - name: exported
        severity: warning
  
  gosec:
    excludes:
      - G104
  
  gocyclo:
    min-complexity: 20  # Validation functions are often complex
  
  stylecheck:
    checks: ["all", "-ST1000"]  # More strict for libraries

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - godot
        - nilnil
        - gocyclo  # Test functions often have high complexity due to table-driven tests
    
    - path: ".*\\.gen\\.go$"
      linters:
        - all
    
    # Allow stuttering for public types that are part of the API
    - linters:
        - revive
      text: "stutters"
      
    - path: vendor/
      linters:
        - all
  
  exclude-dirs:
    - vendor
    - testdata
    - bin
  
  exclude-files:
    - ".*\\.gen\\.go$"
  
  new: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 3m  # Commons is smaller
  tests: true
  concurrency: 4
