with-expecter: true
filename: "mock_{{.InterfaceName | snakecase}}.go"
dir: "test/mocks"
outpkg: "mocks"
packages:
#  github.com/Sokol111/ecommerce-commons/pkg/mongo:
#    interfaces:
#      MongoClient:
#      MongoDatabase:
#      MongoCollection:
#      MongoIndexView:
#      MongoConnect:
