all: false
dir: "{{.InterfaceDir}}"
filename: "mock_{{.InterfaceName | snakecase}}_test.go"
formatter: goimports
pkgname: "{{.SrcPackageName}}"
template: testify
packages:
  github.com/Sokol111/ecommerce-commons/pkg/persistence/mongo:
    config:
      dir: "{{.InterfaceDir}}/mongomock"
      pkgname: "mongomock"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
    interfaces:
      Collection:
