filename: "mock_{{.SrcPackageName | snakecase}}_{{.InterfaceName | snakecase}}.go"
dir: "test/mocks"
pkgname: "mocks"
packages:
  github.com/Sokol111/ecommerce-commons/pkg/kafka/outbox:
    interfaces:
      Outbox:
  github.com/Sokol111/ecommerce-commons/pkg/mongo:
    interfaces:
      TxManager: