package eventgen

import (
	"fmt"
	"path/filepath"

	"github.com/dave/jennifer/jen"
)

const (
	consumerImport = "github.com/Sokol111/ecommerce-commons/pkg/messaging/kafka/consumer"
)

// GenerateHandlers generates the handlers.gen.go file with per-event handler interfaces.
func GenerateHandlers(cfg *Config, payloads []*AvroSchema) error {
	fmt.Println("Generating handler interfaces...")

	f := jen.NewFile(cfg.Package)
	f.HeaderComment("Code generated by eventgen. DO NOT EDIT.")

	f.ImportName(consumerImport, "consumer")

	for _, p := range payloads {
		interfaceName := p.EventName() + "EventHandler"
		methodName := "Handle" + p.EventName()

		f.Commentf("%s is the interface for handling %s events.", interfaceName, p.EventName())
		f.Type().Id(interfaceName).Interface(
			jen.Id(methodName).Params(
				jen.Id("ctx").Qual("context", "Context"),
				jen.Id("event").Op("*").Id(p.EventTypeName()),
			).Error(),
		)
		f.Line()
	}

	outputFile := filepath.Join(cfg.OutputDir, "handlers.gen.go")
	if err := f.Save(outputFile); err != nil {
		return fmt.Errorf("failed to write handlers: %w", err)
	}

	fmt.Println("  Created handlers.gen.go")
	return nil
}
