package eventgen

import (
	"fmt"
	"path/filepath"

	"github.com/dave/jennifer/jen"
)

// GenerateSchemaEmbeddings generates the schemas.gen.go file using jennifer.
func GenerateSchemaEmbeddings(cfg *Config, payloads []*AvroSchema) error {
	fmt.Println("Generating schema embeddings...")

	f := jen.NewFile(cfg.Package)
	f.HeaderComment("Code generated by eventgen. DO NOT EDIT.")

	// Import embed
	f.ImportName("embed", "_")
	f.Anon("embed")

	// Event schema embeddings
	f.Comment("Event schemas with EventMetadata inlined (ready for Avro serialization)")
	for _, p := range payloads {
		f.Comment(fmt.Sprintf("//go:embed schemas/%s.avsc", p.BaseName()))
		f.Var().Id(p.EventName() + "Schema").Index().Byte()
		f.Line()
	}

	outputFile := filepath.Join(cfg.OutputDir, "schemas.gen.go")
	if err := f.Save(outputFile); err != nil {
		return fmt.Errorf("failed to write schemas: %w", err)
	}

	fmt.Println("  Created schemas.gen.go")
	return nil
}
