package eventgen

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/dave/jennifer/jen"
	"github.com/hamba/avro/v2"
	"github.com/hamba/avro/v2/gen"
)

const (
	commonsEventsImport = "github.com/Sokol111/ecommerce-commons/pkg/messaging/kafka/events"
)

// GenerateGoTypes uses hamba/avro/gen for payload types and jennifer for event wrappers.
func GenerateGoTypes(cfg *Config, payloads []*AvroSchema) error {
	fmt.Println("Generating Go types...")

	// Step 1: Generate payload types with hamba/avro/gen (from payload schemas directly)
	if err := generatePayloadTypes(cfg); err != nil {
		return err
	}

	// Step 2: Generate event wrappers with jennifer
	if err := generateEventWrappers(cfg, payloads); err != nil {
		return err
	}

	fmt.Println("  Created types.gen.go and events.gen.go")
	return nil
}

// generatePayloadTypes uses hamba/avro/gen to generate payload structs from payload schemas.
func generatePayloadTypes(cfg *Config) error {
	pattern := filepath.Join(cfg.PayloadsDir, "*_payload.avsc")
	files, err := filepath.Glob(pattern)
	if err != nil {
		return fmt.Errorf("failed to glob payload files: %w", err)
	}

	if len(files) == 0 {
		return fmt.Errorf("no payload files found matching pattern: %s", pattern)
	}

	// Create generator with json:snake tags
	tags := map[string]gen.TagStyle{
		"json": gen.Snake,
	}
	g := gen.NewGenerator(cfg.Package, tags)

	// Parse all schema files
	for _, file := range files {
		schema, parseErr := avro.ParseFiles(file)
		if parseErr != nil {
			return fmt.Errorf("failed to parse schema %s: %w", file, parseErr)
		}
		g.Parse(schema)
	}

	// Write generated code to file
	outputFile := filepath.Join(cfg.OutputDir, "types.gen.go")
	f, err := os.Create(outputFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer f.Close()

	if err := g.Write(f); err != nil {
		return fmt.Errorf("failed to write generated code: %w", err)
	}

	return nil
}

// generateEventWrappers generates event envelope structs using jennifer.
func generateEventWrappers(cfg *Config, payloads []*AvroSchema) error {
	f := jen.NewFile(cfg.Package)
	f.HeaderComment("Code generated by eventgen. DO NOT EDIT.")

	for _, p := range payloads {
		// Event struct with commons.EventMetadata
		f.Commentf("%s is the event envelope for %s.", p.EventTypeName(), p.EventName())
		f.Type().Id(p.EventTypeName()).Struct(
			jen.Id("Metadata").Qual(commonsEventsImport, "EventMetadata").Tag(map[string]string{
				"avro": "metadata",
				"json": "metadata",
			}),
			jen.Id("Payload").Id(p.PayloadTypeName()).Tag(map[string]string{
				"avro": "payload",
				"json": "payload",
			}),
		)
		f.Line()

		// GetMetadata method for Event interface
		f.Func().
			Params(jen.Id("e").Op("*").Id(p.EventTypeName())).
			Id("GetMetadata").
			Params().
			Op("*").Qual(commonsEventsImport, "EventMetadata").
			Block(jen.Return(jen.Op("&").Id("e").Dot("Metadata")))
		f.Line()
	}

	outputFile := filepath.Join(cfg.OutputDir, "events.gen.go")
	return f.Save(outputFile)
}
