package token

import (
	"fmt"

	"github.com/spf13/viper"
)

// Config holds the configuration for PASETO token handling.
type Config struct {
	// PublicKey is the hex-encoded Ed25519 public key for verifying tokens.
	// Required for all services that need to validate incoming tokens.
	PublicKey string `mapstructure:"public-key"`

	// ServiceToken is a pre-generated PASETO token for service-to-service communication.
	// Optional: only needed for services that make outgoing authenticated requests.
	// This token should be generated by auth-service with appropriate permissions.
	ServiceToken string `mapstructure:"service-token"`
}

func newConfig(v *viper.Viper) (Config, error) {
	var cfg Config
	sub := v.Sub("security")
	if sub == nil {
		return cfg, fmt.Errorf("security configuration section is required")
	}

	tokenSub := sub.Sub("token")
	if tokenSub == nil {
		return cfg, fmt.Errorf("security.token configuration section is required")
	}

	if err := tokenSub.Unmarshal(&cfg); err != nil {
		return cfg, fmt.Errorf("failed to load token config: %w", err)
	}

	if cfg.PublicKey == "" {
		return cfg, fmt.Errorf("security.token.public-key is required")
	}

	return cfg, nil
}
