// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mongomock

import (
	"github.com/Sokol111/ecommerce-commons/pkg/persistence/mongo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMongo creates a new instance of MockMongo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMongo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMongo {
	mock := &MockMongo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMongo is an autogenerated mock type for the Mongo type
type MockMongo struct {
	mock.Mock
}

type MockMongo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMongo) EXPECT() *MockMongo_Expecter {
	return &MockMongo_Expecter{mock: &_m.Mock}
}

// GetCollection provides a mock function for the type MockMongo
func (_mock *MockMongo) GetCollection(collection string) mongo.Collection {
	ret := _mock.Called(collection)

	if len(ret) == 0 {
		panic("no return value specified for GetCollection")
	}

	var r0 mongo.Collection
	if returnFunc, ok := ret.Get(0).(func(string) mongo.Collection); ok {
		r0 = returnFunc(collection)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mongo.Collection)
		}
	}
	return r0
}

// MockMongo_GetCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollection'
type MockMongo_GetCollection_Call struct {
	*mock.Call
}

// GetCollection is a helper method to define mock.On call
//   - collection string
func (_e *MockMongo_Expecter) GetCollection(collection interface{}) *MockMongo_GetCollection_Call {
	return &MockMongo_GetCollection_Call{Call: _e.mock.On("GetCollection", collection)}
}

func (_c *MockMongo_GetCollection_Call) Run(run func(collection string)) *MockMongo_GetCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMongo_GetCollection_Call) Return(collection1 mongo.Collection) *MockMongo_GetCollection_Call {
	_c.Call.Return(collection1)
	return _c
}

func (_c *MockMongo_GetCollection_Call) RunAndReturn(run func(collection string) mongo.Collection) *MockMongo_GetCollection_Call {
	_c.Call.Return(run)
	return _c
}

// GetCollectionWithOptions provides a mock function for the type MockMongo
func (_mock *MockMongo) GetCollectionWithOptions(collection string, opts ...mongo.WrapperOption) mongo.Collection {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(collection, opts)
	} else {
		tmpRet = _mock.Called(collection)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetCollectionWithOptions")
	}

	var r0 mongo.Collection
	if returnFunc, ok := ret.Get(0).(func(string, ...mongo.WrapperOption) mongo.Collection); ok {
		r0 = returnFunc(collection, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mongo.Collection)
		}
	}
	return r0
}

// MockMongo_GetCollectionWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollectionWithOptions'
type MockMongo_GetCollectionWithOptions_Call struct {
	*mock.Call
}

// GetCollectionWithOptions is a helper method to define mock.On call
//   - collection string
//   - opts ...mongo.WrapperOption
func (_e *MockMongo_Expecter) GetCollectionWithOptions(collection interface{}, opts ...interface{}) *MockMongo_GetCollectionWithOptions_Call {
	return &MockMongo_GetCollectionWithOptions_Call{Call: _e.mock.On("GetCollectionWithOptions",
		append([]interface{}{collection}, opts...)...)}
}

func (_c *MockMongo_GetCollectionWithOptions_Call) Run(run func(collection string, opts ...mongo.WrapperOption)) *MockMongo_GetCollectionWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []mongo.WrapperOption
		var variadicArgs []mongo.WrapperOption
		if len(args) > 1 {
			variadicArgs = args[1].([]mongo.WrapperOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockMongo_GetCollectionWithOptions_Call) Return(collection1 mongo.Collection) *MockMongo_GetCollectionWithOptions_Call {
	_c.Call.Return(collection1)
	return _c
}

func (_c *MockMongo_GetCollectionWithOptions_Call) RunAndReturn(run func(collection string, opts ...mongo.WrapperOption) mongo.Collection) *MockMongo_GetCollectionWithOptions_Call {
	_c.Call.Return(run)
	return _c
}
