// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mongomock

import (
	"context"

	"github.com/Sokol111/ecommerce-commons/pkg/persistence/mongo"
	mock "github.com/stretchr/testify/mock"
	mongo0 "go.mongodb.org/mongo-driver/mongo"
)

// NewMockMongoAdmin creates a new instance of MockMongoAdmin. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMongoAdmin(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMongoAdmin {
	mock := &MockMongoAdmin{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMongoAdmin is an autogenerated mock type for the MongoAdmin type
type MockMongoAdmin struct {
	mock.Mock
}

type MockMongoAdmin_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMongoAdmin) EXPECT() *MockMongoAdmin_Expecter {
	return &MockMongoAdmin_Expecter{mock: &_m.Mock}
}

// GetCollection provides a mock function for the type MockMongoAdmin
func (_mock *MockMongoAdmin) GetCollection(collection string) mongo.Collection {
	ret := _mock.Called(collection)

	if len(ret) == 0 {
		panic("no return value specified for GetCollection")
	}

	var r0 mongo.Collection
	if returnFunc, ok := ret.Get(0).(func(string) mongo.Collection); ok {
		r0 = returnFunc(collection)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mongo.Collection)
		}
	}
	return r0
}

// MockMongoAdmin_GetCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollection'
type MockMongoAdmin_GetCollection_Call struct {
	*mock.Call
}

// GetCollection is a helper method to define mock.On call
//   - collection string
func (_e *MockMongoAdmin_Expecter) GetCollection(collection interface{}) *MockMongoAdmin_GetCollection_Call {
	return &MockMongoAdmin_GetCollection_Call{Call: _e.mock.On("GetCollection", collection)}
}

func (_c *MockMongoAdmin_GetCollection_Call) Run(run func(collection string)) *MockMongoAdmin_GetCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMongoAdmin_GetCollection_Call) Return(collection1 mongo.Collection) *MockMongoAdmin_GetCollection_Call {
	_c.Call.Return(collection1)
	return _c
}

func (_c *MockMongoAdmin_GetCollection_Call) RunAndReturn(run func(collection string) mongo.Collection) *MockMongoAdmin_GetCollection_Call {
	_c.Call.Return(run)
	return _c
}

// GetCollectionWithOptions provides a mock function for the type MockMongoAdmin
func (_mock *MockMongoAdmin) GetCollectionWithOptions(collection string, opts ...mongo.WrapperOption) mongo.Collection {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(collection, opts)
	} else {
		tmpRet = _mock.Called(collection)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetCollectionWithOptions")
	}

	var r0 mongo.Collection
	if returnFunc, ok := ret.Get(0).(func(string, ...mongo.WrapperOption) mongo.Collection); ok {
		r0 = returnFunc(collection, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mongo.Collection)
		}
	}
	return r0
}

// MockMongoAdmin_GetCollectionWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollectionWithOptions'
type MockMongoAdmin_GetCollectionWithOptions_Call struct {
	*mock.Call
}

// GetCollectionWithOptions is a helper method to define mock.On call
//   - collection string
//   - opts ...mongo.WrapperOption
func (_e *MockMongoAdmin_Expecter) GetCollectionWithOptions(collection interface{}, opts ...interface{}) *MockMongoAdmin_GetCollectionWithOptions_Call {
	return &MockMongoAdmin_GetCollectionWithOptions_Call{Call: _e.mock.On("GetCollectionWithOptions",
		append([]interface{}{collection}, opts...)...)}
}

func (_c *MockMongoAdmin_GetCollectionWithOptions_Call) Run(run func(collection string, opts ...mongo.WrapperOption)) *MockMongoAdmin_GetCollectionWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []mongo.WrapperOption
		var variadicArgs []mongo.WrapperOption
		if len(args) > 1 {
			variadicArgs = args[1].([]mongo.WrapperOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockMongoAdmin_GetCollectionWithOptions_Call) Return(collection1 mongo.Collection) *MockMongoAdmin_GetCollectionWithOptions_Call {
	_c.Call.Return(collection1)
	return _c
}

func (_c *MockMongoAdmin_GetCollectionWithOptions_Call) RunAndReturn(run func(collection string, opts ...mongo.WrapperOption) mongo.Collection) *MockMongoAdmin_GetCollectionWithOptions_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabase provides a mock function for the type MockMongoAdmin
func (_mock *MockMongoAdmin) GetDatabase() *mongo0.Database {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDatabase")
	}

	var r0 *mongo0.Database
	if returnFunc, ok := ret.Get(0).(func() *mongo0.Database); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo0.Database)
		}
	}
	return r0
}

// MockMongoAdmin_GetDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabase'
type MockMongoAdmin_GetDatabase_Call struct {
	*mock.Call
}

// GetDatabase is a helper method to define mock.On call
func (_e *MockMongoAdmin_Expecter) GetDatabase() *MockMongoAdmin_GetDatabase_Call {
	return &MockMongoAdmin_GetDatabase_Call{Call: _e.mock.On("GetDatabase")}
}

func (_c *MockMongoAdmin_GetDatabase_Call) Run(run func()) *MockMongoAdmin_GetDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMongoAdmin_GetDatabase_Call) Return(database *mongo0.Database) *MockMongoAdmin_GetDatabase_Call {
	_c.Call.Return(database)
	return _c
}

func (_c *MockMongoAdmin_GetDatabase_Call) RunAndReturn(run func() *mongo0.Database) *MockMongoAdmin_GetDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// StartSession provides a mock function for the type MockMongoAdmin
func (_mock *MockMongoAdmin) StartSession(ctx context.Context) (mongo0.Session, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartSession")
	}

	var r0 mongo0.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (mongo0.Session, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) mongo0.Session); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mongo0.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMongoAdmin_StartSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartSession'
type MockMongoAdmin_StartSession_Call struct {
	*mock.Call
}

// StartSession is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMongoAdmin_Expecter) StartSession(ctx interface{}) *MockMongoAdmin_StartSession_Call {
	return &MockMongoAdmin_StartSession_Call{Call: _e.mock.On("StartSession", ctx)}
}

func (_c *MockMongoAdmin_StartSession_Call) Run(run func(ctx context.Context)) *MockMongoAdmin_StartSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMongoAdmin_StartSession_Call) Return(session mongo0.Session, err error) *MockMongoAdmin_StartSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockMongoAdmin_StartSession_Call) RunAndReturn(run func(ctx context.Context) (mongo0.Session, error)) *MockMongoAdmin_StartSession_Call {
	_c.Call.Return(run)
	return _c
}
