// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mongomock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

// NewMockSession creates a new instance of MockSession. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSession(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSession {
	mock := &MockSession{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSession is an autogenerated mock type for the Session type
type MockSession struct {
	mock.Mock
}

type MockSession_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSession) EXPECT() *MockSession_Expecter {
	return &MockSession_Expecter{mock: &_m.Mock}
}

// AbortTransaction provides a mock function for the type MockSession
func (_mock *MockSession) AbortTransaction(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AbortTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSession_AbortTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbortTransaction'
type MockSession_AbortTransaction_Call struct {
	*mock.Call
}

// AbortTransaction is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSession_Expecter) AbortTransaction(ctx interface{}) *MockSession_AbortTransaction_Call {
	return &MockSession_AbortTransaction_Call{Call: _e.mock.On("AbortTransaction", ctx)}
}

func (_c *MockSession_AbortTransaction_Call) Run(run func(ctx context.Context)) *MockSession_AbortTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSession_AbortTransaction_Call) Return(err error) *MockSession_AbortTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSession_AbortTransaction_Call) RunAndReturn(run func(ctx context.Context) error) *MockSession_AbortTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// AdvanceClusterTime provides a mock function for the type MockSession
func (_mock *MockSession) AdvanceClusterTime(raw bson.Raw) error {
	ret := _mock.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for AdvanceClusterTime")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(bson.Raw) error); ok {
		r0 = returnFunc(raw)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSession_AdvanceClusterTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdvanceClusterTime'
type MockSession_AdvanceClusterTime_Call struct {
	*mock.Call
}

// AdvanceClusterTime is a helper method to define mock.On call
//   - raw bson.Raw
func (_e *MockSession_Expecter) AdvanceClusterTime(raw interface{}) *MockSession_AdvanceClusterTime_Call {
	return &MockSession_AdvanceClusterTime_Call{Call: _e.mock.On("AdvanceClusterTime", raw)}
}

func (_c *MockSession_AdvanceClusterTime_Call) Run(run func(raw bson.Raw)) *MockSession_AdvanceClusterTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bson.Raw
		if args[0] != nil {
			arg0 = args[0].(bson.Raw)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSession_AdvanceClusterTime_Call) Return(err error) *MockSession_AdvanceClusterTime_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSession_AdvanceClusterTime_Call) RunAndReturn(run func(raw bson.Raw) error) *MockSession_AdvanceClusterTime_Call {
	_c.Call.Return(run)
	return _c
}

// AdvanceOperationTime provides a mock function for the type MockSession
func (_mock *MockSession) AdvanceOperationTime(timestamp *primitive.Timestamp) error {
	ret := _mock.Called(timestamp)

	if len(ret) == 0 {
		panic("no return value specified for AdvanceOperationTime")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*primitive.Timestamp) error); ok {
		r0 = returnFunc(timestamp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSession_AdvanceOperationTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdvanceOperationTime'
type MockSession_AdvanceOperationTime_Call struct {
	*mock.Call
}

// AdvanceOperationTime is a helper method to define mock.On call
//   - timestamp *primitive.Timestamp
func (_e *MockSession_Expecter) AdvanceOperationTime(timestamp interface{}) *MockSession_AdvanceOperationTime_Call {
	return &MockSession_AdvanceOperationTime_Call{Call: _e.mock.On("AdvanceOperationTime", timestamp)}
}

func (_c *MockSession_AdvanceOperationTime_Call) Run(run func(timestamp *primitive.Timestamp)) *MockSession_AdvanceOperationTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *primitive.Timestamp
		if args[0] != nil {
			arg0 = args[0].(*primitive.Timestamp)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSession_AdvanceOperationTime_Call) Return(err error) *MockSession_AdvanceOperationTime_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSession_AdvanceOperationTime_Call) RunAndReturn(run func(timestamp *primitive.Timestamp) error) *MockSession_AdvanceOperationTime_Call {
	_c.Call.Return(run)
	return _c
}

// Client provides a mock function for the type MockSession
func (_mock *MockSession) Client() *mongo.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Client")
	}

	var r0 *mongo.Client
	if returnFunc, ok := ret.Get(0).(func() *mongo.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Client)
		}
	}
	return r0
}

// MockSession_Client_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Client'
type MockSession_Client_Call struct {
	*mock.Call
}

// Client is a helper method to define mock.On call
func (_e *MockSession_Expecter) Client() *MockSession_Client_Call {
	return &MockSession_Client_Call{Call: _e.mock.On("Client")}
}

func (_c *MockSession_Client_Call) Run(run func()) *MockSession_Client_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSession_Client_Call) Return(client *mongo.Client) *MockSession_Client_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockSession_Client_Call) RunAndReturn(run func() *mongo.Client) *MockSession_Client_Call {
	_c.Call.Return(run)
	return _c
}

// ClusterTime provides a mock function for the type MockSession
func (_mock *MockSession) ClusterTime() bson.Raw {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ClusterTime")
	}

	var r0 bson.Raw
	if returnFunc, ok := ret.Get(0).(func() bson.Raw); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bson.Raw)
		}
	}
	return r0
}

// MockSession_ClusterTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterTime'
type MockSession_ClusterTime_Call struct {
	*mock.Call
}

// ClusterTime is a helper method to define mock.On call
func (_e *MockSession_Expecter) ClusterTime() *MockSession_ClusterTime_Call {
	return &MockSession_ClusterTime_Call{Call: _e.mock.On("ClusterTime")}
}

func (_c *MockSession_ClusterTime_Call) Run(run func()) *MockSession_ClusterTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSession_ClusterTime_Call) Return(raw bson.Raw) *MockSession_ClusterTime_Call {
	_c.Call.Return(raw)
	return _c
}

func (_c *MockSession_ClusterTime_Call) RunAndReturn(run func() bson.Raw) *MockSession_ClusterTime_Call {
	_c.Call.Return(run)
	return _c
}

// CommitTransaction provides a mock function for the type MockSession
func (_mock *MockSession) CommitTransaction(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CommitTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSession_CommitTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitTransaction'
type MockSession_CommitTransaction_Call struct {
	*mock.Call
}

// CommitTransaction is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSession_Expecter) CommitTransaction(ctx interface{}) *MockSession_CommitTransaction_Call {
	return &MockSession_CommitTransaction_Call{Call: _e.mock.On("CommitTransaction", ctx)}
}

func (_c *MockSession_CommitTransaction_Call) Run(run func(ctx context.Context)) *MockSession_CommitTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSession_CommitTransaction_Call) Return(err error) *MockSession_CommitTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSession_CommitTransaction_Call) RunAndReturn(run func(ctx context.Context) error) *MockSession_CommitTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// EndSession provides a mock function for the type MockSession
func (_mock *MockSession) EndSession(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockSession_EndSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndSession'
type MockSession_EndSession_Call struct {
	*mock.Call
}

// EndSession is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSession_Expecter) EndSession(ctx interface{}) *MockSession_EndSession_Call {
	return &MockSession_EndSession_Call{Call: _e.mock.On("EndSession", ctx)}
}

func (_c *MockSession_EndSession_Call) Run(run func(ctx context.Context)) *MockSession_EndSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSession_EndSession_Call) Return() *MockSession_EndSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSession_EndSession_Call) RunAndReturn(run func(ctx context.Context)) *MockSession_EndSession_Call {
	_c.Run(run)
	return _c
}

// ID provides a mock function for the type MockSession
func (_mock *MockSession) ID() bson.Raw {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 bson.Raw
	if returnFunc, ok := ret.Get(0).(func() bson.Raw); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bson.Raw)
		}
	}
	return r0
}

// MockSession_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockSession_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockSession_Expecter) ID() *MockSession_ID_Call {
	return &MockSession_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockSession_ID_Call) Run(run func()) *MockSession_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSession_ID_Call) Return(raw bson.Raw) *MockSession_ID_Call {
	_c.Call.Return(raw)
	return _c
}

func (_c *MockSession_ID_Call) RunAndReturn(run func() bson.Raw) *MockSession_ID_Call {
	_c.Call.Return(run)
	return _c
}

// OperationTime provides a mock function for the type MockSession
func (_mock *MockSession) OperationTime() *primitive.Timestamp {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OperationTime")
	}

	var r0 *primitive.Timestamp
	if returnFunc, ok := ret.Get(0).(func() *primitive.Timestamp); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*primitive.Timestamp)
		}
	}
	return r0
}

// MockSession_OperationTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OperationTime'
type MockSession_OperationTime_Call struct {
	*mock.Call
}

// OperationTime is a helper method to define mock.On call
func (_e *MockSession_Expecter) OperationTime() *MockSession_OperationTime_Call {
	return &MockSession_OperationTime_Call{Call: _e.mock.On("OperationTime")}
}

func (_c *MockSession_OperationTime_Call) Run(run func()) *MockSession_OperationTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSession_OperationTime_Call) Return(timestamp *primitive.Timestamp) *MockSession_OperationTime_Call {
	_c.Call.Return(timestamp)
	return _c
}

func (_c *MockSession_OperationTime_Call) RunAndReturn(run func() *primitive.Timestamp) *MockSession_OperationTime_Call {
	_c.Call.Return(run)
	return _c
}

// StartTransaction provides a mock function for the type MockSession
func (_mock *MockSession) StartTransaction(opts ...*options.TransactionOptions) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(opts)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for StartTransaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(...*options.TransactionOptions) error); ok {
		r0 = returnFunc(opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSession_StartTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartTransaction'
type MockSession_StartTransaction_Call struct {
	*mock.Call
}

// StartTransaction is a helper method to define mock.On call
//   - opts ...*options.TransactionOptions
func (_e *MockSession_Expecter) StartTransaction(opts ...interface{}) *MockSession_StartTransaction_Call {
	return &MockSession_StartTransaction_Call{Call: _e.mock.On("StartTransaction",
		append([]interface{}{}, opts...)...)}
}

func (_c *MockSession_StartTransaction_Call) Run(run func(opts ...*options.TransactionOptions)) *MockSession_StartTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*options.TransactionOptions
		var variadicArgs []*options.TransactionOptions
		if len(args) > 0 {
			variadicArgs = args[0].([]*options.TransactionOptions)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockSession_StartTransaction_Call) Return(err error) *MockSession_StartTransaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSession_StartTransaction_Call) RunAndReturn(run func(opts ...*options.TransactionOptions) error) *MockSession_StartTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// WithTransaction provides a mock function for the type MockSession
func (_mock *MockSession) WithTransaction(ctx context.Context, fn func(ctx mongo.SessionContext) (interface{}, error), opts ...*options.TransactionOptions) (interface{}, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, fn, opts)
	} else {
		tmpRet = _mock.Called(ctx, fn)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx mongo.SessionContext) (interface{}, error), ...*options.TransactionOptions) (interface{}, error)); ok {
		return returnFunc(ctx, fn, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx mongo.SessionContext) (interface{}, error), ...*options.TransactionOptions) interface{}); ok {
		r0 = returnFunc(ctx, fn, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, func(ctx mongo.SessionContext) (interface{}, error), ...*options.TransactionOptions) error); ok {
		r1 = returnFunc(ctx, fn, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSession_WithTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTransaction'
type MockSession_WithTransaction_Call struct {
	*mock.Call
}

// WithTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx mongo.SessionContext) (interface{}, error)
//   - opts ...*options.TransactionOptions
func (_e *MockSession_Expecter) WithTransaction(ctx interface{}, fn interface{}, opts ...interface{}) *MockSession_WithTransaction_Call {
	return &MockSession_WithTransaction_Call{Call: _e.mock.On("WithTransaction",
		append([]interface{}{ctx, fn}, opts...)...)}
}

func (_c *MockSession_WithTransaction_Call) Run(run func(ctx context.Context, fn func(ctx mongo.SessionContext) (interface{}, error), opts ...*options.TransactionOptions)) *MockSession_WithTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx mongo.SessionContext) (interface{}, error)
		if args[1] != nil {
			arg1 = args[1].(func(ctx mongo.SessionContext) (interface{}, error))
		}
		var arg2 []*options.TransactionOptions
		var variadicArgs []*options.TransactionOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*options.TransactionOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSession_WithTransaction_Call) Return(ifaceVal interface{}, err error) *MockSession_WithTransaction_Call {
	_c.Call.Return(ifaceVal, err)
	return _c
}

func (_c *MockSession_WithTransaction_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx mongo.SessionContext) (interface{}, error), opts ...*options.TransactionOptions) (interface{}, error)) *MockSession_WithTransaction_Call {
	_c.Call.Return(run)
	return _c
}
