// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mongomock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

// NewMockCollection creates a new instance of MockCollection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCollection(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCollection {
	mock := &MockCollection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCollection is an autogenerated mock type for the Collection type
type MockCollection struct {
	mock.Mock
}

type MockCollection_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCollection) EXPECT() *MockCollection_Expecter {
	return &MockCollection_Expecter{mock: &_m.Mock}
}

// Aggregate provides a mock function for the type MockCollection
func (_mock *MockCollection) Aggregate(ctx context.Context, pipeline interface{}, opts ...*options.AggregateOptions) (*mongo.Cursor, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, pipeline, opts)
	} else {
		tmpRet = _mock.Called(ctx, pipeline)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Aggregate")
	}

	var r0 *mongo.Cursor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.AggregateOptions) (*mongo.Cursor, error)); ok {
		return returnFunc(ctx, pipeline, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.AggregateOptions) *mongo.Cursor); ok {
		r0 = returnFunc(ctx, pipeline, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Cursor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...*options.AggregateOptions) error); ok {
		r1 = returnFunc(ctx, pipeline, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollection_Aggregate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Aggregate'
type MockCollection_Aggregate_Call struct {
	*mock.Call
}

// Aggregate is a helper method to define mock.On call
//   - ctx context.Context
//   - pipeline interface{}
//   - opts ...*options.AggregateOptions
func (_e *MockCollection_Expecter) Aggregate(ctx interface{}, pipeline interface{}, opts ...interface{}) *MockCollection_Aggregate_Call {
	return &MockCollection_Aggregate_Call{Call: _e.mock.On("Aggregate",
		append([]interface{}{ctx, pipeline}, opts...)...)}
}

func (_c *MockCollection_Aggregate_Call) Run(run func(ctx context.Context, pipeline interface{}, opts ...*options.AggregateOptions)) *MockCollection_Aggregate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*options.AggregateOptions
		var variadicArgs []*options.AggregateOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*options.AggregateOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCollection_Aggregate_Call) Return(cursor *mongo.Cursor, err error) *MockCollection_Aggregate_Call {
	_c.Call.Return(cursor, err)
	return _c
}

func (_c *MockCollection_Aggregate_Call) RunAndReturn(run func(ctx context.Context, pipeline interface{}, opts ...*options.AggregateOptions) (*mongo.Cursor, error)) *MockCollection_Aggregate_Call {
	_c.Call.Return(run)
	return _c
}

// BulkWrite provides a mock function for the type MockCollection
func (_mock *MockCollection) BulkWrite(ctx context.Context, models []mongo.WriteModel, opts ...*options.BulkWriteOptions) (*mongo.BulkWriteResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, models, opts)
	} else {
		tmpRet = _mock.Called(ctx, models)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BulkWrite")
	}

	var r0 *mongo.BulkWriteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []mongo.WriteModel, ...*options.BulkWriteOptions) (*mongo.BulkWriteResult, error)); ok {
		return returnFunc(ctx, models, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []mongo.WriteModel, ...*options.BulkWriteOptions) *mongo.BulkWriteResult); ok {
		r0 = returnFunc(ctx, models, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.BulkWriteResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []mongo.WriteModel, ...*options.BulkWriteOptions) error); ok {
		r1 = returnFunc(ctx, models, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollection_BulkWrite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkWrite'
type MockCollection_BulkWrite_Call struct {
	*mock.Call
}

// BulkWrite is a helper method to define mock.On call
//   - ctx context.Context
//   - models []mongo.WriteModel
//   - opts ...*options.BulkWriteOptions
func (_e *MockCollection_Expecter) BulkWrite(ctx interface{}, models interface{}, opts ...interface{}) *MockCollection_BulkWrite_Call {
	return &MockCollection_BulkWrite_Call{Call: _e.mock.On("BulkWrite",
		append([]interface{}{ctx, models}, opts...)...)}
}

func (_c *MockCollection_BulkWrite_Call) Run(run func(ctx context.Context, models []mongo.WriteModel, opts ...*options.BulkWriteOptions)) *MockCollection_BulkWrite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []mongo.WriteModel
		if args[1] != nil {
			arg1 = args[1].([]mongo.WriteModel)
		}
		var arg2 []*options.BulkWriteOptions
		var variadicArgs []*options.BulkWriteOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*options.BulkWriteOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCollection_BulkWrite_Call) Return(bulkWriteResult *mongo.BulkWriteResult, err error) *MockCollection_BulkWrite_Call {
	_c.Call.Return(bulkWriteResult, err)
	return _c
}

func (_c *MockCollection_BulkWrite_Call) RunAndReturn(run func(ctx context.Context, models []mongo.WriteModel, opts ...*options.BulkWriteOptions) (*mongo.BulkWriteResult, error)) *MockCollection_BulkWrite_Call {
	_c.Call.Return(run)
	return _c
}

// CountDocuments provides a mock function for the type MockCollection
func (_mock *MockCollection) CountDocuments(ctx context.Context, filter interface{}, opts ...*options.CountOptions) (int64, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CountDocuments")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.CountOptions) (int64, error)); ok {
		return returnFunc(ctx, filter, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.CountOptions) int64); ok {
		r0 = returnFunc(ctx, filter, opts...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...*options.CountOptions) error); ok {
		r1 = returnFunc(ctx, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollection_CountDocuments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountDocuments'
type MockCollection_CountDocuments_Call struct {
	*mock.Call
}

// CountDocuments is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts ...*options.CountOptions
func (_e *MockCollection_Expecter) CountDocuments(ctx interface{}, filter interface{}, opts ...interface{}) *MockCollection_CountDocuments_Call {
	return &MockCollection_CountDocuments_Call{Call: _e.mock.On("CountDocuments",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MockCollection_CountDocuments_Call) Run(run func(ctx context.Context, filter interface{}, opts ...*options.CountOptions)) *MockCollection_CountDocuments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*options.CountOptions
		var variadicArgs []*options.CountOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*options.CountOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCollection_CountDocuments_Call) Return(n int64, err error) *MockCollection_CountDocuments_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCollection_CountDocuments_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, opts ...*options.CountOptions) (int64, error)) *MockCollection_CountDocuments_Call {
	_c.Call.Return(run)
	return _c
}

// Database provides a mock function for the type MockCollection
func (_mock *MockCollection) Database() *mongo.Database {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Database")
	}

	var r0 *mongo.Database
	if returnFunc, ok := ret.Get(0).(func() *mongo.Database); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Database)
		}
	}
	return r0
}

// MockCollection_Database_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Database'
type MockCollection_Database_Call struct {
	*mock.Call
}

// Database is a helper method to define mock.On call
func (_e *MockCollection_Expecter) Database() *MockCollection_Database_Call {
	return &MockCollection_Database_Call{Call: _e.mock.On("Database")}
}

func (_c *MockCollection_Database_Call) Run(run func()) *MockCollection_Database_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCollection_Database_Call) Return(database *mongo.Database) *MockCollection_Database_Call {
	_c.Call.Return(database)
	return _c
}

func (_c *MockCollection_Database_Call) RunAndReturn(run func() *mongo.Database) *MockCollection_Database_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function for the type MockCollection
func (_mock *MockCollection) DeleteMany(ctx context.Context, filter interface{}, opts ...*options.DeleteOptions) (*mongo.DeleteResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 *mongo.DeleteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.DeleteOptions) (*mongo.DeleteResult, error)); ok {
		return returnFunc(ctx, filter, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.DeleteOptions) *mongo.DeleteResult); ok {
		r0 = returnFunc(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.DeleteResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...*options.DeleteOptions) error); ok {
		r1 = returnFunc(ctx, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollection_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type MockCollection_DeleteMany_Call struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts ...*options.DeleteOptions
func (_e *MockCollection_Expecter) DeleteMany(ctx interface{}, filter interface{}, opts ...interface{}) *MockCollection_DeleteMany_Call {
	return &MockCollection_DeleteMany_Call{Call: _e.mock.On("DeleteMany",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MockCollection_DeleteMany_Call) Run(run func(ctx context.Context, filter interface{}, opts ...*options.DeleteOptions)) *MockCollection_DeleteMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*options.DeleteOptions
		var variadicArgs []*options.DeleteOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*options.DeleteOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCollection_DeleteMany_Call) Return(deleteResult *mongo.DeleteResult, err error) *MockCollection_DeleteMany_Call {
	_c.Call.Return(deleteResult, err)
	return _c
}

func (_c *MockCollection_DeleteMany_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, opts ...*options.DeleteOptions) (*mongo.DeleteResult, error)) *MockCollection_DeleteMany_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOne provides a mock function for the type MockCollection
func (_mock *MockCollection) DeleteOne(ctx context.Context, filter interface{}, opts ...*options.DeleteOptions) (*mongo.DeleteResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteOne")
	}

	var r0 *mongo.DeleteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.DeleteOptions) (*mongo.DeleteResult, error)); ok {
		return returnFunc(ctx, filter, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.DeleteOptions) *mongo.DeleteResult); ok {
		r0 = returnFunc(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.DeleteResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...*options.DeleteOptions) error); ok {
		r1 = returnFunc(ctx, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollection_DeleteOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOne'
type MockCollection_DeleteOne_Call struct {
	*mock.Call
}

// DeleteOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts ...*options.DeleteOptions
func (_e *MockCollection_Expecter) DeleteOne(ctx interface{}, filter interface{}, opts ...interface{}) *MockCollection_DeleteOne_Call {
	return &MockCollection_DeleteOne_Call{Call: _e.mock.On("DeleteOne",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MockCollection_DeleteOne_Call) Run(run func(ctx context.Context, filter interface{}, opts ...*options.DeleteOptions)) *MockCollection_DeleteOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*options.DeleteOptions
		var variadicArgs []*options.DeleteOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*options.DeleteOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCollection_DeleteOne_Call) Return(deleteResult *mongo.DeleteResult, err error) *MockCollection_DeleteOne_Call {
	_c.Call.Return(deleteResult, err)
	return _c
}

func (_c *MockCollection_DeleteOne_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, opts ...*options.DeleteOptions) (*mongo.DeleteResult, error)) *MockCollection_DeleteOne_Call {
	_c.Call.Return(run)
	return _c
}

// Distinct provides a mock function for the type MockCollection
func (_mock *MockCollection) Distinct(ctx context.Context, fieldName string, filter interface{}, opts ...*options.DistinctOptions) ([]interface{}, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, fieldName, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, fieldName, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Distinct")
	}

	var r0 []interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}, ...*options.DistinctOptions) ([]interface{}, error)); ok {
		return returnFunc(ctx, fieldName, filter, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}, ...*options.DistinctOptions) []interface{}); ok {
		r0 = returnFunc(ctx, fieldName, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, interface{}, ...*options.DistinctOptions) error); ok {
		r1 = returnFunc(ctx, fieldName, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollection_Distinct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Distinct'
type MockCollection_Distinct_Call struct {
	*mock.Call
}

// Distinct is a helper method to define mock.On call
//   - ctx context.Context
//   - fieldName string
//   - filter interface{}
//   - opts ...*options.DistinctOptions
func (_e *MockCollection_Expecter) Distinct(ctx interface{}, fieldName interface{}, filter interface{}, opts ...interface{}) *MockCollection_Distinct_Call {
	return &MockCollection_Distinct_Call{Call: _e.mock.On("Distinct",
		append([]interface{}{ctx, fieldName, filter}, opts...)...)}
}

func (_c *MockCollection_Distinct_Call) Run(run func(ctx context.Context, fieldName string, filter interface{}, opts ...*options.DistinctOptions)) *MockCollection_Distinct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []*options.DistinctOptions
		var variadicArgs []*options.DistinctOptions
		if len(args) > 3 {
			variadicArgs = args[3].([]*options.DistinctOptions)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockCollection_Distinct_Call) Return(ifaceVals []interface{}, err error) *MockCollection_Distinct_Call {
	_c.Call.Return(ifaceVals, err)
	return _c
}

func (_c *MockCollection_Distinct_Call) RunAndReturn(run func(ctx context.Context, fieldName string, filter interface{}, opts ...*options.DistinctOptions) ([]interface{}, error)) *MockCollection_Distinct_Call {
	_c.Call.Return(run)
	return _c
}

// Drop provides a mock function for the type MockCollection
func (_mock *MockCollection) Drop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Drop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCollection_Drop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Drop'
type MockCollection_Drop_Call struct {
	*mock.Call
}

// Drop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCollection_Expecter) Drop(ctx interface{}) *MockCollection_Drop_Call {
	return &MockCollection_Drop_Call{Call: _e.mock.On("Drop", ctx)}
}

func (_c *MockCollection_Drop_Call) Run(run func(ctx context.Context)) *MockCollection_Drop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCollection_Drop_Call) Return(err error) *MockCollection_Drop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCollection_Drop_Call) RunAndReturn(run func(ctx context.Context) error) *MockCollection_Drop_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockCollection
func (_mock *MockCollection) Find(ctx context.Context, filter interface{}, opts ...*options.FindOptions) (*mongo.Cursor, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *mongo.Cursor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.FindOptions) (*mongo.Cursor, error)); ok {
		return returnFunc(ctx, filter, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.FindOptions) *mongo.Cursor); ok {
		r0 = returnFunc(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Cursor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...*options.FindOptions) error); ok {
		r1 = returnFunc(ctx, filter, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollection_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockCollection_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts ...*options.FindOptions
func (_e *MockCollection_Expecter) Find(ctx interface{}, filter interface{}, opts ...interface{}) *MockCollection_Find_Call {
	return &MockCollection_Find_Call{Call: _e.mock.On("Find",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MockCollection_Find_Call) Run(run func(ctx context.Context, filter interface{}, opts ...*options.FindOptions)) *MockCollection_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*options.FindOptions
		var variadicArgs []*options.FindOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*options.FindOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCollection_Find_Call) Return(cursor *mongo.Cursor, err error) *MockCollection_Find_Call {
	_c.Call.Return(cursor, err)
	return _c
}

func (_c *MockCollection_Find_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, opts ...*options.FindOptions) (*mongo.Cursor, error)) *MockCollection_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function for the type MockCollection
func (_mock *MockCollection) FindOne(ctx context.Context, filter interface{}, opts ...*options.FindOneOptions) *mongo.SingleResult {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 *mongo.SingleResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.FindOneOptions) *mongo.SingleResult); ok {
		r0 = returnFunc(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.SingleResult)
		}
	}
	return r0
}

// MockCollection_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type MockCollection_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts ...*options.FindOneOptions
func (_e *MockCollection_Expecter) FindOne(ctx interface{}, filter interface{}, opts ...interface{}) *MockCollection_FindOne_Call {
	return &MockCollection_FindOne_Call{Call: _e.mock.On("FindOne",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MockCollection_FindOne_Call) Run(run func(ctx context.Context, filter interface{}, opts ...*options.FindOneOptions)) *MockCollection_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*options.FindOneOptions
		var variadicArgs []*options.FindOneOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*options.FindOneOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCollection_FindOne_Call) Return(singleResult *mongo.SingleResult) *MockCollection_FindOne_Call {
	_c.Call.Return(singleResult)
	return _c
}

func (_c *MockCollection_FindOne_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, opts ...*options.FindOneOptions) *mongo.SingleResult) *MockCollection_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// FindOneAndDelete provides a mock function for the type MockCollection
func (_mock *MockCollection) FindOneAndDelete(ctx context.Context, filter interface{}, opts ...*options.FindOneAndDeleteOptions) *mongo.SingleResult {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndDelete")
	}

	var r0 *mongo.SingleResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.FindOneAndDeleteOptions) *mongo.SingleResult); ok {
		r0 = returnFunc(ctx, filter, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.SingleResult)
		}
	}
	return r0
}

// MockCollection_FindOneAndDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOneAndDelete'
type MockCollection_FindOneAndDelete_Call struct {
	*mock.Call
}

// FindOneAndDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - opts ...*options.FindOneAndDeleteOptions
func (_e *MockCollection_Expecter) FindOneAndDelete(ctx interface{}, filter interface{}, opts ...interface{}) *MockCollection_FindOneAndDelete_Call {
	return &MockCollection_FindOneAndDelete_Call{Call: _e.mock.On("FindOneAndDelete",
		append([]interface{}{ctx, filter}, opts...)...)}
}

func (_c *MockCollection_FindOneAndDelete_Call) Run(run func(ctx context.Context, filter interface{}, opts ...*options.FindOneAndDeleteOptions)) *MockCollection_FindOneAndDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*options.FindOneAndDeleteOptions
		var variadicArgs []*options.FindOneAndDeleteOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*options.FindOneAndDeleteOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCollection_FindOneAndDelete_Call) Return(singleResult *mongo.SingleResult) *MockCollection_FindOneAndDelete_Call {
	_c.Call.Return(singleResult)
	return _c
}

func (_c *MockCollection_FindOneAndDelete_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, opts ...*options.FindOneAndDeleteOptions) *mongo.SingleResult) *MockCollection_FindOneAndDelete_Call {
	_c.Call.Return(run)
	return _c
}

// FindOneAndReplace provides a mock function for the type MockCollection
func (_mock *MockCollection) FindOneAndReplace(ctx context.Context, filter interface{}, replacement interface{}, opts ...*options.FindOneAndReplaceOptions) *mongo.SingleResult {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, replacement, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter, replacement)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndReplace")
	}

	var r0 *mongo.SingleResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...*options.FindOneAndReplaceOptions) *mongo.SingleResult); ok {
		r0 = returnFunc(ctx, filter, replacement, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.SingleResult)
		}
	}
	return r0
}

// MockCollection_FindOneAndReplace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOneAndReplace'
type MockCollection_FindOneAndReplace_Call struct {
	*mock.Call
}

// FindOneAndReplace is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - replacement interface{}
//   - opts ...*options.FindOneAndReplaceOptions
func (_e *MockCollection_Expecter) FindOneAndReplace(ctx interface{}, filter interface{}, replacement interface{}, opts ...interface{}) *MockCollection_FindOneAndReplace_Call {
	return &MockCollection_FindOneAndReplace_Call{Call: _e.mock.On("FindOneAndReplace",
		append([]interface{}{ctx, filter, replacement}, opts...)...)}
}

func (_c *MockCollection_FindOneAndReplace_Call) Run(run func(ctx context.Context, filter interface{}, replacement interface{}, opts ...*options.FindOneAndReplaceOptions)) *MockCollection_FindOneAndReplace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []*options.FindOneAndReplaceOptions
		var variadicArgs []*options.FindOneAndReplaceOptions
		if len(args) > 3 {
			variadicArgs = args[3].([]*options.FindOneAndReplaceOptions)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockCollection_FindOneAndReplace_Call) Return(singleResult *mongo.SingleResult) *MockCollection_FindOneAndReplace_Call {
	_c.Call.Return(singleResult)
	return _c
}

func (_c *MockCollection_FindOneAndReplace_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, replacement interface{}, opts ...*options.FindOneAndReplaceOptions) *mongo.SingleResult) *MockCollection_FindOneAndReplace_Call {
	_c.Call.Return(run)
	return _c
}

// FindOneAndUpdate provides a mock function for the type MockCollection
func (_mock *MockCollection) FindOneAndUpdate(ctx context.Context, filter interface{}, update interface{}, opts ...*options.FindOneAndUpdateOptions) *mongo.SingleResult {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, update, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter, update)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for FindOneAndUpdate")
	}

	var r0 *mongo.SingleResult
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...*options.FindOneAndUpdateOptions) *mongo.SingleResult); ok {
		r0 = returnFunc(ctx, filter, update, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.SingleResult)
		}
	}
	return r0
}

// MockCollection_FindOneAndUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOneAndUpdate'
type MockCollection_FindOneAndUpdate_Call struct {
	*mock.Call
}

// FindOneAndUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - update interface{}
//   - opts ...*options.FindOneAndUpdateOptions
func (_e *MockCollection_Expecter) FindOneAndUpdate(ctx interface{}, filter interface{}, update interface{}, opts ...interface{}) *MockCollection_FindOneAndUpdate_Call {
	return &MockCollection_FindOneAndUpdate_Call{Call: _e.mock.On("FindOneAndUpdate",
		append([]interface{}{ctx, filter, update}, opts...)...)}
}

func (_c *MockCollection_FindOneAndUpdate_Call) Run(run func(ctx context.Context, filter interface{}, update interface{}, opts ...*options.FindOneAndUpdateOptions)) *MockCollection_FindOneAndUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []*options.FindOneAndUpdateOptions
		var variadicArgs []*options.FindOneAndUpdateOptions
		if len(args) > 3 {
			variadicArgs = args[3].([]*options.FindOneAndUpdateOptions)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockCollection_FindOneAndUpdate_Call) Return(singleResult *mongo.SingleResult) *MockCollection_FindOneAndUpdate_Call {
	_c.Call.Return(singleResult)
	return _c
}

func (_c *MockCollection_FindOneAndUpdate_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, update interface{}, opts ...*options.FindOneAndUpdateOptions) *mongo.SingleResult) *MockCollection_FindOneAndUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Indexes provides a mock function for the type MockCollection
func (_mock *MockCollection) Indexes() mongo.IndexView {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Indexes")
	}

	var r0 mongo.IndexView
	if returnFunc, ok := ret.Get(0).(func() mongo.IndexView); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(mongo.IndexView)
	}
	return r0
}

// MockCollection_Indexes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Indexes'
type MockCollection_Indexes_Call struct {
	*mock.Call
}

// Indexes is a helper method to define mock.On call
func (_e *MockCollection_Expecter) Indexes() *MockCollection_Indexes_Call {
	return &MockCollection_Indexes_Call{Call: _e.mock.On("Indexes")}
}

func (_c *MockCollection_Indexes_Call) Run(run func()) *MockCollection_Indexes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCollection_Indexes_Call) Return(indexView mongo.IndexView) *MockCollection_Indexes_Call {
	_c.Call.Return(indexView)
	return _c
}

func (_c *MockCollection_Indexes_Call) RunAndReturn(run func() mongo.IndexView) *MockCollection_Indexes_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function for the type MockCollection
func (_mock *MockCollection) InsertMany(ctx context.Context, documents []interface{}, opts ...*options.InsertManyOptions) (*mongo.InsertManyResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, documents, opts)
	} else {
		tmpRet = _mock.Called(ctx, documents)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 *mongo.InsertManyResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []interface{}, ...*options.InsertManyOptions) (*mongo.InsertManyResult, error)); ok {
		return returnFunc(ctx, documents, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []interface{}, ...*options.InsertManyOptions) *mongo.InsertManyResult); ok {
		r0 = returnFunc(ctx, documents, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.InsertManyResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []interface{}, ...*options.InsertManyOptions) error); ok {
		r1 = returnFunc(ctx, documents, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollection_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockCollection_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - documents []interface{}
//   - opts ...*options.InsertManyOptions
func (_e *MockCollection_Expecter) InsertMany(ctx interface{}, documents interface{}, opts ...interface{}) *MockCollection_InsertMany_Call {
	return &MockCollection_InsertMany_Call{Call: _e.mock.On("InsertMany",
		append([]interface{}{ctx, documents}, opts...)...)}
}

func (_c *MockCollection_InsertMany_Call) Run(run func(ctx context.Context, documents []interface{}, opts ...*options.InsertManyOptions)) *MockCollection_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []interface{}
		if args[1] != nil {
			arg1 = args[1].([]interface{})
		}
		var arg2 []*options.InsertManyOptions
		var variadicArgs []*options.InsertManyOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*options.InsertManyOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCollection_InsertMany_Call) Return(insertManyResult *mongo.InsertManyResult, err error) *MockCollection_InsertMany_Call {
	_c.Call.Return(insertManyResult, err)
	return _c
}

func (_c *MockCollection_InsertMany_Call) RunAndReturn(run func(ctx context.Context, documents []interface{}, opts ...*options.InsertManyOptions) (*mongo.InsertManyResult, error)) *MockCollection_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// InsertOne provides a mock function for the type MockCollection
func (_mock *MockCollection) InsertOne(ctx context.Context, document interface{}, opts ...*options.InsertOneOptions) (*mongo.InsertOneResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, document, opts)
	} else {
		tmpRet = _mock.Called(ctx, document)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for InsertOne")
	}

	var r0 *mongo.InsertOneResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.InsertOneOptions) (*mongo.InsertOneResult, error)); ok {
		return returnFunc(ctx, document, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, ...*options.InsertOneOptions) *mongo.InsertOneResult); ok {
		r0 = returnFunc(ctx, document, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.InsertOneResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, ...*options.InsertOneOptions) error); ok {
		r1 = returnFunc(ctx, document, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollection_InsertOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertOne'
type MockCollection_InsertOne_Call struct {
	*mock.Call
}

// InsertOne is a helper method to define mock.On call
//   - ctx context.Context
//   - document interface{}
//   - opts ...*options.InsertOneOptions
func (_e *MockCollection_Expecter) InsertOne(ctx interface{}, document interface{}, opts ...interface{}) *MockCollection_InsertOne_Call {
	return &MockCollection_InsertOne_Call{Call: _e.mock.On("InsertOne",
		append([]interface{}{ctx, document}, opts...)...)}
}

func (_c *MockCollection_InsertOne_Call) Run(run func(ctx context.Context, document interface{}, opts ...*options.InsertOneOptions)) *MockCollection_InsertOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []*options.InsertOneOptions
		var variadicArgs []*options.InsertOneOptions
		if len(args) > 2 {
			variadicArgs = args[2].([]*options.InsertOneOptions)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockCollection_InsertOne_Call) Return(insertOneResult *mongo.InsertOneResult, err error) *MockCollection_InsertOne_Call {
	_c.Call.Return(insertOneResult, err)
	return _c
}

func (_c *MockCollection_InsertOne_Call) RunAndReturn(run func(ctx context.Context, document interface{}, opts ...*options.InsertOneOptions) (*mongo.InsertOneResult, error)) *MockCollection_InsertOne_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockCollection
func (_mock *MockCollection) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCollection_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockCollection_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockCollection_Expecter) Name() *MockCollection_Name_Call {
	return &MockCollection_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockCollection_Name_Call) Run(run func()) *MockCollection_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCollection_Name_Call) Return(s string) *MockCollection_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCollection_Name_Call) RunAndReturn(run func() string) *MockCollection_Name_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceOne provides a mock function for the type MockCollection
func (_mock *MockCollection) ReplaceOne(ctx context.Context, filter interface{}, replacement interface{}, opts ...*options.ReplaceOptions) (*mongo.UpdateResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, replacement, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter, replacement)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ReplaceOne")
	}

	var r0 *mongo.UpdateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...*options.ReplaceOptions) (*mongo.UpdateResult, error)); ok {
		return returnFunc(ctx, filter, replacement, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...*options.ReplaceOptions) *mongo.UpdateResult); ok {
		r0 = returnFunc(ctx, filter, replacement, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.UpdateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, interface{}, ...*options.ReplaceOptions) error); ok {
		r1 = returnFunc(ctx, filter, replacement, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollection_ReplaceOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceOne'
type MockCollection_ReplaceOne_Call struct {
	*mock.Call
}

// ReplaceOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - replacement interface{}
//   - opts ...*options.ReplaceOptions
func (_e *MockCollection_Expecter) ReplaceOne(ctx interface{}, filter interface{}, replacement interface{}, opts ...interface{}) *MockCollection_ReplaceOne_Call {
	return &MockCollection_ReplaceOne_Call{Call: _e.mock.On("ReplaceOne",
		append([]interface{}{ctx, filter, replacement}, opts...)...)}
}

func (_c *MockCollection_ReplaceOne_Call) Run(run func(ctx context.Context, filter interface{}, replacement interface{}, opts ...*options.ReplaceOptions)) *MockCollection_ReplaceOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []*options.ReplaceOptions
		var variadicArgs []*options.ReplaceOptions
		if len(args) > 3 {
			variadicArgs = args[3].([]*options.ReplaceOptions)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockCollection_ReplaceOne_Call) Return(updateResult *mongo.UpdateResult, err error) *MockCollection_ReplaceOne_Call {
	_c.Call.Return(updateResult, err)
	return _c
}

func (_c *MockCollection_ReplaceOne_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, replacement interface{}, opts ...*options.ReplaceOptions) (*mongo.UpdateResult, error)) *MockCollection_ReplaceOne_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMany provides a mock function for the type MockCollection
func (_mock *MockCollection) UpdateMany(ctx context.Context, filter interface{}, update interface{}, opts ...*options.UpdateOptions) (*mongo.UpdateResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, update, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter, update)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateMany")
	}

	var r0 *mongo.UpdateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...*options.UpdateOptions) (*mongo.UpdateResult, error)); ok {
		return returnFunc(ctx, filter, update, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...*options.UpdateOptions) *mongo.UpdateResult); ok {
		r0 = returnFunc(ctx, filter, update, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.UpdateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, interface{}, ...*options.UpdateOptions) error); ok {
		r1 = returnFunc(ctx, filter, update, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollection_UpdateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMany'
type MockCollection_UpdateMany_Call struct {
	*mock.Call
}

// UpdateMany is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - update interface{}
//   - opts ...*options.UpdateOptions
func (_e *MockCollection_Expecter) UpdateMany(ctx interface{}, filter interface{}, update interface{}, opts ...interface{}) *MockCollection_UpdateMany_Call {
	return &MockCollection_UpdateMany_Call{Call: _e.mock.On("UpdateMany",
		append([]interface{}{ctx, filter, update}, opts...)...)}
}

func (_c *MockCollection_UpdateMany_Call) Run(run func(ctx context.Context, filter interface{}, update interface{}, opts ...*options.UpdateOptions)) *MockCollection_UpdateMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []*options.UpdateOptions
		var variadicArgs []*options.UpdateOptions
		if len(args) > 3 {
			variadicArgs = args[3].([]*options.UpdateOptions)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockCollection_UpdateMany_Call) Return(updateResult *mongo.UpdateResult, err error) *MockCollection_UpdateMany_Call {
	_c.Call.Return(updateResult, err)
	return _c
}

func (_c *MockCollection_UpdateMany_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, update interface{}, opts ...*options.UpdateOptions) (*mongo.UpdateResult, error)) *MockCollection_UpdateMany_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOne provides a mock function for the type MockCollection
func (_mock *MockCollection) UpdateOne(ctx context.Context, filter interface{}, update interface{}, opts ...*options.UpdateOptions) (*mongo.UpdateResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, filter, update, opts)
	} else {
		tmpRet = _mock.Called(ctx, filter, update)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateOne")
	}

	var r0 *mongo.UpdateResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...*options.UpdateOptions) (*mongo.UpdateResult, error)); ok {
		return returnFunc(ctx, filter, update, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, interface{}, interface{}, ...*options.UpdateOptions) *mongo.UpdateResult); ok {
		r0 = returnFunc(ctx, filter, update, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.UpdateResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, interface{}, interface{}, ...*options.UpdateOptions) error); ok {
		r1 = returnFunc(ctx, filter, update, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCollection_UpdateOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOne'
type MockCollection_UpdateOne_Call struct {
	*mock.Call
}

// UpdateOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter interface{}
//   - update interface{}
//   - opts ...*options.UpdateOptions
func (_e *MockCollection_Expecter) UpdateOne(ctx interface{}, filter interface{}, update interface{}, opts ...interface{}) *MockCollection_UpdateOne_Call {
	return &MockCollection_UpdateOne_Call{Call: _e.mock.On("UpdateOne",
		append([]interface{}{ctx, filter, update}, opts...)...)}
}

func (_c *MockCollection_UpdateOne_Call) Run(run func(ctx context.Context, filter interface{}, update interface{}, opts ...*options.UpdateOptions)) *MockCollection_UpdateOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 []*options.UpdateOptions
		var variadicArgs []*options.UpdateOptions
		if len(args) > 3 {
			variadicArgs = args[3].([]*options.UpdateOptions)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockCollection_UpdateOne_Call) Return(updateResult *mongo.UpdateResult, err error) *MockCollection_UpdateOne_Call {
	_c.Call.Return(updateResult, err)
	return _c
}

func (_c *MockCollection_UpdateOne_Call) RunAndReturn(run func(ctx context.Context, filter interface{}, update interface{}, opts ...*options.UpdateOptions) (*mongo.UpdateResult, error)) *MockCollection_UpdateOne_Call {
	_c.Call.Return(run)
	return _c
}
